# Generated by Django 4.1.7 on 2023-02-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_uuid',
            field=models.CharField(default='e75f4c51-375d-49c6-b502-94139e377f7a', editable=False, max_length=120, primary_key=True, serialize=False, verbose_name='user_uuid'),
        ),
    ]
