# Generated by Django 4.1.7 on 2023-02-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0002_alter_user_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_uuid',
            field=models.CharField(default='a5af6768-de79-4ca5-a21a-883008d87e85', editable=False, max_length=120, primary_key=True, serialize=False, verbose_name='user_uuid'),
        ),
    ]
