# Generated by Django 4.1.7 on 2023-02-15 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0003_alter_user_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_uuid',
            field=models.CharField(default='e357b08c-9d92-4ab9-8f77-155e44f2886b', editable=False, max_length=120, primary_key=True, serialize=False, verbose_name='user_uuid'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_uuid', models.CharField(editable=False, max_length=120, primary_key=True, serialize=False, verbose_name='task_uuid')),
                ('task_title', models.CharField(max_length=120, verbose_name='task_title')),
                ('task_is_completed', models.BooleanField(default=False, verbose_name='task_is_completed')),
                ('task_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='to_do.user', verbose_name='task_owner')),
            ],
        ),
    ]
